In [1]:
print("Welcome to learning Numpy with Subhashish")

Welcome to learning Numpy with Subhashish


In [2]:
import numpy as np

In [3]:
data = np.random.randn(2,3)

In [4]:
print(data)

[[-0.00788198  0.01937742  0.68480502]
 [ 0.31812372  0.03934374 -0.57967823]]


In [5]:
# Manipulation of data is so easy with numpy
data * 10

array([[-0.07881984,  0.19377422,  6.84805025],
       [ 3.18123724,  0.39343738, -5.79678229]])

In [6]:
# In order to fetch the dimension of array, we can do something like this/
data.shape

(2, 3)

In [7]:
# In order to check the datatype of element inside my np array
data.dtype

dtype('float64')

## Creating ndarrays
In order to create ndarrays, the easiest method is to use np.array method.

In [8]:
data1 = [1,2,3.5,6,7]

In [9]:
arr1 = np.array(data1)

In [10]:
arr1

array([1. , 2. , 3.5, 6. , 7. ])

In [11]:
# for multi-dimensional array, we can follow the same procedure
data2 = [[1,2,3,4,5],[6,7,8,9,10]]

In [12]:
arr2 = np.array(data2)

In [13]:
arr2.shape

(2, 5)

In [14]:
arr2.dtype

dtype('int64')

In [15]:
# In order to check the dimension of the array we can use ndim function as well
arr2.ndim

2

In [16]:
# We can create an array with n dimension and fill up all the values with zero
data3 = np.zeros(10)
data4 = np.zeros((2,3))

In [17]:
# data3
data4

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
data5 = np.empty((2,3))
data5

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
nestedarr = np.empty((2,3,2))

In [20]:
nestedarr

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [21]:
# we can use arange function to define the lenght of an array
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Datatypes for ndarrays
We can specify data-type or dtype for a np array as shown below

In [22]:
arr1 = np.array([1,2,3],dtype=np.float64)

In [23]:
arr2 = np.array([1,2,3], dtype=np.int32)

In [24]:
arr1

array([1., 2., 3.])

In [25]:
arr2

array([1, 2, 3], dtype=int32)

In [26]:
arr2.dtype

dtype('int32')

In [27]:
# Type casting in an numpy array can be done in following way
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int64')

In [28]:
float_arr = arr.astype(np.float64)

In [29]:
float_arr.dtype

dtype('float64')

In [30]:
# We can type cast with reference to another numpy array as well as shown below
int_array = np.arange(10)
float_array = np.array([1.1,1.2,1.3,1.4], dtype=np.float64)
converted = int_array.astype(float_arr.dtype)
converted

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

## Arithmetic with NumPy Arrays
Batch operations on data can be done without using any kind of loops in numpy

In [31]:
arr = np.array([[1,2,3],[1,2,3]])
arr

array([[1, 2, 3],
       [1, 2, 3]])

In [32]:
arr * arr

array([[1, 4, 9],
       [1, 4, 9]])

In [33]:
arr

array([[1, 2, 3],
       [1, 2, 3]])

In [34]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

In [35]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [36]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

## Basic indexing and slicing

In [37]:
arr = np.arange(10)

In [38]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
arr[0]

0

In [40]:
arr[5:8]

array([5, 6, 7])

In [41]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
# We can manipulate the array using scalar value as shown in the below code. This is also known as broadcasting
arr[5:8] = 10

In [43]:
arr

array([ 0,  1,  2,  3,  4, 10, 10, 10,  8,  9])

In [44]:
arr_slice = arr[5:8]

In [45]:
arr_slice

array([10, 10, 10])

In [46]:
# Inorder to reflect the value to whole array, we can do bear slicing as well as shown below.
arr_slice[:]=64

In [47]:
arr_slice

array([64, 64, 64])

In [48]:
# We can also copy a slice of array without affecting the real one
arr
copied = arr[5:8].copy()

In [49]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [50]:
copied

array([64, 64, 64])

In [51]:
# Slicing through a multi-dimensional array is more fun
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr[2]

array([7, 8, 9])

In [52]:
arr[2][1]

8