In [1]:
print("Welcome to learning Numpy with Subhashish")

Welcome to learning Numpy with Subhashish


In [2]:
import numpy as np

In [3]:
data = np.random.randn(2,3)

In [4]:
print(data)

[[ 0.64124612 -0.90967996  0.74639066]
 [-0.11023917  1.17382662  1.67313261]]


In [5]:
# Manipulation of data is so easy with numpy
data * 10

array([[ 6.41246122, -9.09679965,  7.46390658],
       [-1.10239174, 11.73826617, 16.73132614]])

In [6]:
# In order to fetch the dimension of array, we can do something like this/
data.shape

(2, 3)

In [7]:
# In order to check the datatype of element inside my np array
data.dtype

dtype('float64')

## Creating ndarrays
In order to create ndarrays, the easiest method is to use np.array method.

In [8]:
data1 = [1,2,3.5,6,7]

In [9]:
arr1 = np.array(data1)

In [10]:
arr1

array([1. , 2. , 3.5, 6. , 7. ])

In [11]:
# for multi-dimensional array, we can follow the same procedure
data2 = [[1,2,3,4,5],[6,7,8,9,10]]

In [12]:
arr2 = np.array(data2)

In [13]:
arr2.shape

(2, 5)

In [14]:
arr2.dtype

dtype('int64')

In [15]:
# In order to check the dimension of the array we can use ndim function as well
arr2.ndim

2

In [16]:
# We can create an array with n dimension and fill up all the values with zero
data3 = np.zeros(10)
data4 = np.zeros((2,3))

In [17]:
# data3
data4

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
data5 = np.empty((2,3))
data5

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
nestedarr = np.empty((2,3,2))

In [20]:
nestedarr

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [21]:
# we can use arange function to define the lenght of an array
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Datatypes for ndarrays
We can specify data-type or dtype for a np array as shown below

In [22]:
arr1 = np.array([1,2,3],dtype=np.float64)

In [23]:
arr2 = np.array([1,2,3], dtype=np.int32)

In [24]:
arr1

array([1., 2., 3.])

In [25]:
arr2

array([1, 2, 3], dtype=int32)

In [26]:
arr2.dtype

dtype('int32')

In [27]:
# Type casting in an numpy array can be done in following way
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int64')

In [28]:
float_arr = arr.astype(np.float64)

In [29]:
float_arr.dtype

dtype('float64')

In [30]:
# We can type cast with reference to another numpy array as well as shown below
int_array = np.arange(10)
float_array = np.array([1.1,1.2,1.3,1.4], dtype=np.float64)
converted = int_array.astype(float_arr.dtype)
converted

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

## Arithmetic with NumPy Arrays
Batch operations on data can be done without using any kind of loops in numpy

In [31]:
arr = np.array([[1,2,3],[1,2,3]])
arr

array([[1, 2, 3],
       [1, 2, 3]])

In [32]:
arr * arr

array([[1, 4, 9],
       [1, 4, 9]])

In [33]:
arr

array([[1, 2, 3],
       [1, 2, 3]])

In [34]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

In [35]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [36]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

## Basic indexing and slicing

In [37]:
arr = np.arange(10)

In [38]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
arr[0]

0

In [40]:
arr[5:8]

array([5, 6, 7])

In [41]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
# We can manipulate the array using scalar value as shown in the below code. This is also known as broadcasting
arr[5:8] = 10

In [43]:
arr

array([ 0,  1,  2,  3,  4, 10, 10, 10,  8,  9])

In [44]:
arr_slice = arr[5:8]

In [45]:
arr_slice

array([10, 10, 10])

In [46]:
# Inorder to reflect the value to whole array, we can do bear slicing as well as shown below.
arr_slice[:]=64

In [47]:
arr_slice

array([64, 64, 64])

In [48]:
# We can also copy a slice of array without affecting the real one
arr
copied = arr[5:8].copy()

In [49]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [50]:
copied

array([64, 64, 64])

In [51]:
# Slicing through a multi-dimensional array is more fun
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr[2]

array([7, 8, 9])

In [52]:
arr[2][1]

8

In [53]:
# Indexing and slicing a 3d array
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [54]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [55]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
arr3d[0] = 42

In [57]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

## Boolean Indexing

In [58]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])

In [59]:
data = np.random.randn(7,4)

In [60]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [61]:
data

array([[ 1.38756079, -0.83389407,  0.17281384, -0.26227434],
       [ 1.0399991 , -0.36943238, -2.34223894, -0.5507614 ],
       [ 0.11007956, -0.77665397,  0.76203265,  0.1116506 ],
       [ 1.64405327,  0.62787379,  0.14610316, -0.04215558],
       [ 0.26766588, -0.73164714,  0.75049114, -1.11253874],
       [ 1.9606635 , -0.00863615, -0.59209297,  2.75370714],
       [-1.02794422,  1.72904397, -0.82798605, -0.27785094]])

In [62]:
names=='Bob'

array([ True, False, False,  True, False, False, False])

In [63]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [64]:
data[names == 'Bob']

array([[ 1.38756079, -0.83389407,  0.17281384, -0.26227434],
       [ 1.64405327,  0.62787379,  0.14610316, -0.04215558]])

In [65]:
# So what actually happen here was, data was manipuated by the rows where the value was retireved as true.

In [66]:
data[names=='Bob', 2:]

array([[ 0.17281384, -0.26227434],
       [ 0.14610316, -0.04215558]])

In [67]:
# negative selection
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [68]:
data[~(names == 'Bob')]

array([[ 1.0399991 , -0.36943238, -2.34223894, -0.5507614 ],
       [ 0.11007956, -0.77665397,  0.76203265,  0.1116506 ],
       [ 0.26766588, -0.73164714,  0.75049114, -1.11253874],
       [ 1.9606635 , -0.00863615, -0.59209297,  2.75370714],
       [-1.02794422,  1.72904397, -0.82798605, -0.27785094]])

In [69]:
# using mutiple conditions can be something like this
mask = (names == 'Bob') | (names == 'Will')

In [70]:
mask

array([ True, False,  True,  True,  True, False, False])

In [71]:
data[mask] # This always creates a copy of a data

array([[ 1.38756079, -0.83389407,  0.17281384, -0.26227434],
       [ 0.11007956, -0.77665397,  0.76203265,  0.1116506 ],
       [ 1.64405327,  0.62787379,  0.14610316, -0.04215558],
       [ 0.26766588, -0.73164714,  0.75049114, -1.11253874]])

In [72]:
data

array([[ 1.38756079, -0.83389407,  0.17281384, -0.26227434],
       [ 1.0399991 , -0.36943238, -2.34223894, -0.5507614 ],
       [ 0.11007956, -0.77665397,  0.76203265,  0.1116506 ],
       [ 1.64405327,  0.62787379,  0.14610316, -0.04215558],
       [ 0.26766588, -0.73164714,  0.75049114, -1.11253874],
       [ 1.9606635 , -0.00863615, -0.59209297,  2.75370714],
       [-1.02794422,  1.72904397, -0.82798605, -0.27785094]])

In [73]:
# We can even go further with conditioning,

In [74]:
data[data<0] = 0

In [75]:
data

array([[1.38756079, 0.        , 0.17281384, 0.        ],
       [1.0399991 , 0.        , 0.        , 0.        ],
       [0.11007956, 0.        , 0.76203265, 0.1116506 ],
       [1.64405327, 0.62787379, 0.14610316, 0.        ],
       [0.26766588, 0.        , 0.75049114, 0.        ],
       [1.9606635 , 0.        , 0.        , 2.75370714],
       [0.        , 1.72904397, 0.        , 0.        ]])

In [76]:
data[names!='Joe'] = 7

In [77]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [1.0399991 , 0.        , 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [1.9606635 , 0.        , 0.        , 2.75370714],
       [0.        , 1.72904397, 0.        , 0.        ]])

## Fancy-Indexing

In [78]:
arr = np.empty((8,4))

In [79]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [80]:
for i in range(8):
    arr[i] = i

In [81]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [82]:
arr[[3,4,0,6]]

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [83]:
arr = np.arange(32).reshape((8,4))

In [84]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [85]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

## Transposing Arrays and Swapping Axes

In [86]:
arr = np.arange(15).reshape((3,5))

In [87]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [88]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [89]:
arr = np.random.randn(6,3)

In [90]:
np.dot(arr.T,arr)

array([[ 3.80985053, -1.36951847, -1.80637998],
       [-1.36951847, 13.07035377, -2.5094301 ],
       [-1.80637998, -2.5094301 ,  2.35312074]])

## Universal Functions: Fast Element-Wise Array

In [91]:
# Lets try sqrt the arrays
arr = np.arange(10)

In [92]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [93]:
arr
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [94]:
x = np.random.randn(8)

In [95]:
y = np.random.randn(8)

In [96]:
np.maximum(x,y)

array([ 0.07460041,  0.53067343,  0.84466891,  1.23217256,  1.12502211,
        2.33359228,  0.12087966, -1.10046177])

## Conditional expression in numpy

In [97]:
xarr = np.array([1.1,1.2,1.3,1.4,1.5])

In [98]:
yarr = np.array([2.1,2.2,2.3,2.4,2.5])

In [99]:
cond = yarr != 2.5

In [100]:
cond

array([ True,  True,  True,  True, False])

In [101]:
result = [(x if c else y)
           for x,y,c in zip(xarr,yarr,cond)
         ]

In [102]:
result

[1.1, 1.2, 1.3, 1.4, 2.5]

In [103]:
result = np.where(cond,xarr,yarr)

In [104]:
result

array([1.1, 1.2, 1.3, 1.4, 2.5])

In [105]:
arr = np.random.randn(4,4)

In [106]:
result = np.where(arr>0,2,-2)

In [107]:
result

array([[-2,  2,  2, -2],
       [-2, -2,  2,  2],
       [ 2, -2,  2, -2],
       [-2, -2, -2,  2]])

## Mathematical and Statistical Methods

In [108]:
arr = np.random.randn(5,4)

In [109]:
arr

array([[ 0.17388389, -0.46243211, -1.46338109, -0.90043225],
       [-0.40853901,  0.02818284, -0.17839224,  0.18299759],
       [ 0.00664697, -0.43047757,  1.00403172, -0.78311634],
       [ 1.34869043, -0.72974395, -0.03257834,  1.08940102],
       [ 0.31121951,  0.91982347,  0.31327992, -0.60760421]])

In [110]:
arr.mean()

-0.0309269876895339

In [111]:
np.mean(arr)

-0.0309269876895339

In [112]:
arr.sum()

-0.618539753790678

## Methods for Boolean Arrays

In [113]:
arr = np.random.randn(100)

In [114]:
arr

array([-0.56426252,  0.6713728 , -0.08507236, -1.82161296,  0.17768019,
        0.43969509,  0.45261491, -0.01906401,  0.08157101,  0.85639242,
       -1.29465894, -0.5596416 , -1.62131294, -0.66622721,  1.3484639 ,
       -1.40149058, -0.98509487, -1.75999277,  1.02268213, -0.25618728,
        0.74439371, -1.30438916,  0.15528957, -1.89059645,  2.09027733,
        2.94619283, -1.39863139,  1.27776804, -0.99121796, -0.55548389,
       -0.76802031,  1.14709637, -0.19077663, -1.45872459, -0.37401105,
       -0.09479805, -1.04965023,  1.74847141, -0.20843973,  0.94284271,
        0.1474646 ,  1.22818638,  0.90605333,  1.43828014, -1.02125919,
       -1.20266079, -1.4657373 , -0.57161041,  0.02967015, -1.13147128,
       -0.13555375,  0.37357285, -0.92561088, -0.68544588,  0.68314917,
        1.15656033, -0.66931946, -0.5642749 , -1.20661408,  0.30458133,
        0.79462605, -1.66584743,  1.27701152, -1.40626951,  0.34791238,
       -0.59064641,  0.07763562,  1.85937457,  0.08835182, -0.48

In [115]:
(arr>0).sum()

48

In [116]:
# any and all methods. any works like a or. If any value is true, than it returns true whereas all is and. All values must be tru
bools = np.array([False,False,True,False])

In [117]:
bools.any()

True

In [118]:
bools.all()

False

## File input and output with Arrays

In [119]:
arr = np.arange(10)

In [120]:
np.save('some_array',arr) # This will save the file to the disk

In [121]:
np.load('some_array.npy') # This will load the file from the disk

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Linear Algebra

In [122]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [123]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [124]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [125]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [126]:
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [127]:
from numpy.linalg import inv, qr

In [128]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])